spring:
  application.name: FX-service-example
  datasource.url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true

server:
  error:
    include-binding-errors: always

nbp:
  base-url: https://api.nbp.pl/api
  connect-timeout: 5s
  read-timeout: 10s
